# Generated by Django 6.0.6 on 2026-06-24 14:25

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of the text content.', max_length=64)),
                ('embedding_model', models.CharField(max_length=100)),
                ('dimension', models.IntegerField(default=384, help_text='Dimension of the stored embedding vector.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_hash', 'embedding_model'], name='ingestion_e_content_88141a_idx')],
                'unique_together': {('content_hash', 'embedding_model')},
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('partial_success', 'Partial Success'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('total_chunks_created', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique trace identifier for end-to-end observability.')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('parser_version', models.CharField(default='1.0', max_length=20)),
                ('chunker_version', models.CharField(default='1.0', max_length=20)),
                ('embedding_version', models.CharField(default='1.0', max_length=20)),
                ('stage_timings', models.JSONField(blank=True, default=dict, help_text='Wall-clock time per stage: {"discover": 0.1, "parse": 2.3, ...}')),
                ('completed_file_ids', models.JSONField(blank=True, default=list, help_text='UUIDs of SourceDocuments that completed successfully (for resume).')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='Structured errors: [{"file": "...", "stage": "parse", "error": "...", "category": "parse_error"}]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parser_version', models.CharField(default='1.0', max_length=20)),
                ('chunker_version', models.CharField(default='1.0', max_length=20)),
                ('embedding_model', models.CharField(blank=True, default='', help_text='Name of the embedding model used during indexing.', max_length=100)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=20)),
                ('index_version', models.CharField(default='1.0', help_text='Composite version identifier for the full pipeline run.', max_length=20)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('inherit', 'Inherit from Project'), ('visible', 'Visible'), ('hidden', 'Hidden')], default='inherit', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['file_path'],
                'unique_together': {('project', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('heading_context', models.CharField(blank=True, default='', max_length=512)),
                ('symbol_context', models.CharField(blank=True, default='', max_length=512)),
                ('chunk_type', models.CharField(choices=[('code', 'Code'), ('markdown', 'Markdown'), ('text', 'Plain Text'), ('config', 'Configuration'), ('docstring', 'Docstring')], default='text', max_length=20)),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_model', models.CharField(blank=True, default='', help_text='Embedding model used to generate the vector for this chunk.', max_length=100)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=20)),
                ('is_stale', models.BooleanField(default=False, help_text='True when pipeline versions change and this chunk has not been re-embedded.')),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA-256 of content. Used for embedding deduplication.', max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='projects.project')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.sourcedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['project', 'chunk_type'], name='ingestion_d_project_9c0a17_idx'), models.Index(fields=['project', 'is_stale'], name='ingestion_d_project_4c4fc9_idx'), models.Index(fields=['content_hash'], name='ingestion_d_content_c34532_idx')],
            },
        ),
    ]
