# Generated by Django 6.0.6 on 2026-06-24 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('upload', 'File Upload'), ('local', 'Local Directory'), ('github', 'GitHub Repository')], default='upload', max_length=20)),
                ('source_path', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('created', 'Created'), ('ingesting', 'Ingesting'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retrieval_mode', models.CharField(choices=[('vector', 'Vector (Semantic)'), ('hybrid', 'Hybrid (Semantic + Lexical)'), ('lexical', 'Lexical (Full-Text)')], default='vector', max_length=20)),
                ('retrieval_top_k', models.IntegerField(default=10)),
                ('max_context_tokens', models.IntegerField(default=3000)),
                ('owner_id', models.CharField(blank=True, default='system', help_text='Owner identifier — plain string, decoupled from auth model.', max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
