# Generated by Django 6.0.6 on 2026-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20)),
                ('telemetry_enabled', models.BooleanField(default=False)),
                ('ollama_endpoint', models.CharField(default='http://localhost:11434', max_length=255)),
                ('max_concurrent_jobs', models.IntegerField(default=4)),
                ('vector_retention_days', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
