# Generated by Django 6.0.6 on 2026-06-24 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('raw_context', models.TextField(blank=True, default='')),
                ('generation_time_ms', models.FloatField(blank=True, null=True)),
                ('retrieval_time_ms', models.FloatField(blank=True, null=True)),
                ('chunks_retrieved', models.IntegerField(default=0)),
                ('chunks_used', models.IntegerField(default=0)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient Evidence')], default='medium', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique trace identifier for end-to-end query observability.')),
                ('retrieval_mode', models.CharField(default='vector', help_text='Retrieval strategy used: vector, hybrid, or lexical.', max_length=20)),
                ('top_k_requested', models.IntegerField(default=10)),
                ('generation_model', models.CharField(blank=True, default='', help_text='LLM model name used for answer generation.', max_length=100)),
                ('embedding_model', models.CharField(blank=True, default='', help_text='Embedding model used for query vector.', max_length=100)),
                ('prompt_token_estimate', models.IntegerField(default=0, help_text='Estimated token count of the full prompt sent to the LLM.')),
                ('context_token_estimate', models.IntegerField(default=0, help_text='Estimated token count of the assembled context.')),
                ('avg_similarity_score', models.FloatField(blank=True, null=True)),
                ('max_similarity_score', models.FloatField(blank=True, null=True)),
                ('min_similarity_score', models.FloatField(blank=True, null=True)),
                ('score_std_dev', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedChunkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('similarity_score', models.FloatField()),
                ('used_in_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='ingestion.documentchunk')),
                ('query_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_chunks', to='query.querysession')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
